import streamlit as st
from fpdf import FPDF
import pytesseract
from PIL import Image, ImageDraw
import datetime
import io

# --- CONFIG & BRANDING ---
TORO_SLATE_BLUE = (84, 106, 118)  # #546A76
TORO_LIGHT_GREY = (248, 249, 250)

st.set_page_config(page_title="Toro | Tech Pack & Feedback Engine", layout="wide")

# Custom CSS for Toro Branding
st.markdown(f"""
    <style>
    .main {{ background-color: #f9fafb; }}
    .stButton>button {{ background-color: #546A76; color: white; border-radius: 4px; border: none; height: 3em; }}
    .stButton>button:hover {{ background-color: #3d4d56; color: white; }}
    .toro-header {{ background-color: white; padding: 20px; border-bottom: 3px solid #546A76; text-align: center; margin-bottom: 20px; }}
    </style>
    """, unsafe_allow_html=True)

# --- PDF GENERATOR CLASS ---
class ToroPDF(FPDF):
    def header(self):
        # Header Background
        self.set_fill_color(84, 106, 118)
        self.rect(0, 0, 210, 35, 'F')
        
        # Title & Branding
        self.set_text_color(255, 255, 255)
        self.set_font('Arial', 'B', 16)
        self.set_xy(10, 10)
        self.cell(0, 10, "TORO SUPPLY CHAIN SOLUTIONS", ln=True)
        self.set_font('Arial', '', 10)
        self.cell(0, 5, "TECHNICAL PRODUCT SPECIFICATION", ln=True)
        
        self.set_xy(150, 10)
        self.set_font('Arial', 'B', 12)
        self.cell(50, 10, f"ROUND: {st.session_state.get('ver', 'P1')}", align='R')
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'PROPERTY OF TORO SUPPLY CHAIN SOLUTIONS | CONFIDENTIAL | Generated by Toro AI Engine', 0, 0, 'C')

# --- LOGIC FUNCTIONS ---
def perform_ocr(image):
    try:
        return pytesseract.image_to_string(image)
    except:
        return "OCR Error: Tesseract not configured. Please enter text manually."

def create_pdf(prod_name, version, description, image, mode, comments=""):
    pdf = ToroPDF()
    pdf.add_page()
    
    # Metadata Box
    pdf.set_fill_color(240, 240, 240)
    pdf.rect(10, 40, 190, 20, 'F')
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.set_xy(15, 42)
    pdf.cell(95, 8, f"PRODUCT: {prod_name}")
    pdf.cell(95, 8, f"DATE: {datetime.date.today().strftime('%m/%d/%Y')}", ln=True)
    pdf.set_xy(15, 50)
    pdf.set_font('Arial', '', 10)
    pdf.cell(95, 8, f"VERSION: {version}")
    pdf.cell(95, 8, f"TYPE: {mode}")

    # Image Placement
    if image:
        # Save temp image for PDF
        img_path = "temp_print_img.png"
        image.save(img_path)
        pdf.image(img_path, x=10, y=65, w=120)

    # Right Sidebar: Comments/Specs
    pdf.set_fill_color(248, 249, 250)
    pdf.rect(135, 65, 65, 150, 'F')
    pdf.set_xy(140, 70)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "SPECIFICATIONS" if mode == "Tech Pack" else "FEEDBACK")
    
    pdf.set_font('Arial', '', 9)
    pdf.set_xy(140, 85)
    pdf.multi_cell(55, 5, description if mode == "Tech Pack" else comments)

    return pdf.output(dest='S').encode('latin-1')

# --- USER INTERFACE ---
st.markdown('<div class="toro-header"><h1>TORO AI DESIGN ENGINE</h1></div>', unsafe_allow_html=True)

mode = st.radio("Select Workflow Mode", ["Tech Pack Generator", "Feedback Card Generator"], horizontal=True)

col1, col2 = st.columns([1, 1.2])

with col1:
    st.subheader("1. Input Data")
    prod_name = st.text_input("Product Name", "Toro Wool Socks")
    version = st.selectbox("Version/Round", ["P1", "P2", "P3", "R1", "R2"])
    st.session_state['ver'] = version
    
    uploaded_file = st.file_uploader("Upload Product Image or Previous Tech Pack", type=["png", "jpg", "jpeg"])
    
    if uploaded_file:
        img = Image.open(uploaded_file)
        st.image(img, caption="Uploaded Input", use_column_width=True)
        
        if st.button("Run Toro OCR Scan"):
            with st.spinner("Extracting text data..."):
                ocr_result = perform_ocr(img)
                st.session_state['ocr_text'] = ocr_result
                st.success("OCR Scan Complete")

    description = st.text_area("Product Description / Tech Specs", 
                               value=st.session_state.get('ocr_text', ""),
                               placeholder="Enter materials, Pantone colors, and features...")

    feedback_comments = ""
    if mode == "Feedback Card Generator":
        feedback_comments = st.text_area("Sample Feedback Comments", placeholder="1. Move logo higher\n2. Change blue to PMS 546A76...")

with col2:
    st.subheader("2. Preview & Export")
    if uploaded_file:
        st.info("Drafting Toro-Branded Document...")
        
        # Display a visual simulation of the PDF
        st.markdown(f"""
        <div style="border: 1px solid #ccc; padding: 20px; background: white;">
            <h3 style="color: #546A76; border-bottom: 2px solid #546A76;">{prod_name} - {version}</h3>
            <p><b>Status:</b> Ready for Export</p>
            <p><b>Target Colors:</b> Automated Pantone Selection Active (PMS 546A76)</p>
        </div>
        """, unsafe_allow_html=True)
        
        # Generate PDF Button
        pdf_bytes = create_pdf(prod_name, version, description, Image.open(uploaded_file), mode, feedback_comments)
        
        st.download_button(
            label="📥 Download Toro PDF",
            data=pdf_bytes,
            file_name=f"Toro_{prod_name}_{version}.pdf",
            mime="application/pdf"
        )
    else:
        st.write("Upload an image to generate preview and export buttons.")

st.divider()
st.caption("© 2024 Toro Supply Chain Solutions | 5PL Design Infrastructure Tool")